name: scheduler_updater
description: An updater for schedule data
version: 0.0.1

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  googleapis_auth:
    git: https://github.com/dart-lang/googleapis_auth.git
  scheduler_base:
    git: https://github.com/denniskaselow/scheduler_base.git
